CREATE TABLE "role_groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "create_time" timestamp NOT NULL,
  "create_user" varchar(255) NOT NULL,
  "update_time" timestamp,
  "update_user" varchar(255)
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "account" varchar(255) NOT NULL,
  "mail" varchar(255) NOT NULL,
  "phone" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "birthday" timestamp NOT NULL,
  "create_time" timestamp NOT NULL,
  "create_user" varchar(255) NOT NULL,
  "update_time" timestamp,
  "update_user" varchar(255)
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "create_time" timestamp NOT NULL,
  "create_user" varchar(255) NOT NULL,
  "update_time" timestamp,
  "update_user" varchar(255)
);

CREATE TABLE "permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "create_time" timestamp NOT NULL,
  "create_user" varchar(255) NOT NULL,
  "update_time" timestamp,
  "update_user" varchar(255)
);

CREATE TABLE "roles_permissions_relationships" (
  "role_id" integer NOT NULL,
  "permissions_id" integer NOT NULL,
  "is_create" integer NOT NULL DEFAULT 0,
  "is_update" integer NOT NULL DEFAULT 0,
  "is_read" integer NOT NULL DEFAULT 0,
  "is_delete" integer NOT NULL DEFAULT 0,
  "is_verify" integer NOT NULL DEFAULT 0,
  "create_time" timestamp NOT NULL,
  "create_user" varchar(255) NOT NULL,
  "update_time" timestamp,
  "update_user" varchar(255),
  PRIMARY KEY ("role_id", "permissions_id")
);

CREATE TABLE "users_role_groups_relationships" (
  "user_id" integer NOT NULL,
  "role_group_id" integer NOT NULL,
  "create_time" timestamp NOT NULL,
  "create_user" varchar(255) NOT NULL,
  "update_time" timestamp,
  "update_user" varchar(255),
  PRIMARY KEY ("user_id", "role_group_id")
);

CREATE TABLE "roles_role_groups_relationships" (
  "role_id" integer NOT NULL,
  "role_group_id" integer NOT NULL,
  "create_time" timestamp NOT NULL,
  "create_user" varchar(255) NOT NULL,
  "update_time" timestamp,
  "update_user" varchar(255),
  PRIMARY KEY ("role_id", "role_group_id")
);

ALTER TABLE "roles_permissions_relationships" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "roles_permissions_relationships" ADD FOREIGN KEY ("permissions_id") REFERENCES "permissions" ("id");

ALTER TABLE "users_role_groups_relationships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_role_groups_relationships" ADD FOREIGN KEY ("role_group_id") REFERENCES "role_groups" ("id");

ALTER TABLE "roles_role_groups_relationships" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "roles_role_groups_relationships" ADD FOREIGN KEY ("role_group_id") REFERENCES "role_groups" ("id");
